Introduce kotlin coroutines API
JetBrains/teamcity-rest-client pull request #120
Opened 2023-09-05 00:12 UTC by shchuko

Backward compatibility is preserved: blocking API is implemented using `runBlocking { }` wrappers.

`TeamCityInstanceBuilder` is introduced, so I had to deprecate a few methods it replaces.

2023-09-06 08:33 UTC, Andronnix requested changes
That's a mega job! I'm torn a little bit though if this should be 1.22 or 2.0, as the change is significant

2023-09-06 08:33 UTC, Andronnix commented on README.md
> +val tc = TeamCityInstanceBuilder("https://myserver.local")
The advantage to the old example is that it is working against a real server, just need to copy and paste it. Would be great to have another working example with coroutines against teamcity.jetbrains.com

2023-09-06 08:53 UTC, shchuko commented on teamcity-rest-client-impl/src/main/kotlin/org/jetbrains/teamcity/rest/builder.kt
> +    override fun equals(other: Any?): Boolean {
Used to compare builders in DeprecatedFactoryTest

https://github.com/shchuko/teamcity-rest-client/blob/c4e6ffa3bffe94191492b497b487518eb232d109/teamcity-rest-client-impl/src/test/kotlin/org/jetbrains/teamcity/rest/DeprecatedFactoryTest.kt#L25

2023-09-06 11:40 UTC, shchuko commented
> I'm torn a little bit though if this should be 1.22 or 2.0, as the change is significant

If we meet [SEMVER](https://semver.org/) rules:
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes

There's no need to increment MAJOR version and 1.22 is OK because the changes are backward-compatible.

2023-09-07 16:06 UTC, shchuko commented
I've also added retries configuration support, to be actively used at least in IntelliJ build scripts.

2023-09-25 22:30 UTC, shchuko commented
Rebased onto recent master

2023-09-26 09:00 UTC, merged